# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-566cfd1e-0ca1-4f73-b2ca-7f622660cd1e";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-566cfd1e-0ca1-4f73-b2ca-7f622660cd1e".device = "/dev/disk/by-uuid/566cfd1e-0ca1-4f73-b2ca-7f622660cd1e";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-566cfd1e-0ca1-4f73-b2ca-7f622660cd1e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-566cfd1e-0ca1-4f73-b2ca-7f622660cd1e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/051C-9FD4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
