#!/usr/bin/env bash

discover_hosts() {
  mapfile -t HOSTS < <(nix eval --json "$WINTIX_FLAKE_REF#nixosConfigurations" --apply 'x: builtins.attrNames x' | jq -r '.[]')
  ((${#HOSTS[@]})) || die "No Wintix NixOS host configurations were discovered."
}

detect_ram() {
  local meminfo=${1:-/proc/meminfo} mem_kib
  mem_kib=$(awk '$1 == "MemTotal:" { print $2; exit }' "$meminfo" 2>/dev/null || true)
  [[ $mem_kib =~ ^[0-9]+$ ]] || die "Could not detect physical RAM from $meminfo."
  # Keep all conversion integral: MemTotal is KiB, while swapDevices.size uses
  # MiB. Round RAM upward to MiB and swap upward to a whole GiB so common
  # nominal capacities such as 16/32/64 GiB retain their hibernation headroom.
  ((mem_kib >= 131072 && mem_kib <= 9007199253690368)) || \
    die "Detected physical RAM value is outside the supported range: $mem_kib KiB."
  RAM_SIZE_MIB=$(((mem_kib + 1023) / 1024))
  SWAP_SIZE_MIB=$((((RAM_SIZE_MIB + 1023) / 1024) * 1024))
  ((RAM_SIZE_MIB > 0 && SWAP_SIZE_MIB > 0)) || die "Detected physical RAM produced an invalid swap size."
}

format_mib() {
  local mib=$1 whole tenths
  whole=$((mib / 1024))
  tenths=$((((mib % 1024) * 10 + 512) / 1024))
  if ((tenths == 10)); then whole=$((whole + 1)); tenths=0; fi
  printf '%d.%d GiB (%d MiB)' "$whole" "$tenths" "$mib"
}

select_host() {
  discover_hosts
  SELECTED_HOST=$(gum choose --header "Select Wintix host" "${HOSTS[@]}")
  # Existing normal users are authoritative. A host with zero or multiple users
  # needs a host-side definition rather than an installer guess.
  mapfile -t NORMAL_USERS < <(nix eval --json "$WINTIX_FLAKE_REF#nixosConfigurations.${SELECTED_HOST}.config.users.users" --apply 'u: builtins.filter (n: u.${n}.isNormalUser) (builtins.attrNames u)' | jq -r '.[]')
  [[ ${#NORMAL_USERS[@]} -eq 1 ]] || die "Host ${SELECTED_HOST} must define exactly one normal user for unattended selection."
  USERNAME=${NORMAL_USERS[0]}
  HOSTNAME=$(gum input --prompt "Hostname: " --value "$SELECTED_HOST")
  [[ $HOSTNAME =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]] || die "Invalid hostname (use letters, digits, and internal hyphens; maximum 63 characters)."
}

select_mode() {
  local choice
  choice=$(gum choose --header "Installation mode" \
    "wipe | Wipe entire disk (all data destroyed)" \
    "free | Use contiguous unallocated space (preserve partitions)" \
    "replace | Replace one existing partition (retain GPT entry)")
  INSTALL_MODE=${choice%% *}
  case $INSTALL_MODE in
    wipe) TARGET_PARTITION=""; ESP_PARTITION="generated by Disko" ;;
    free) require_gpt_for_partial_mode; select_esp "$SELECTED_DISK"; select_free_region ;;
    replace) require_gpt_for_partial_mode; select_esp "$SELECTED_DISK"; select_replace_partition ;;
  esac
}

review_plan() {
  local target preserved destroyed partitions partition
  case $INSTALL_MODE in
    wipe)
      target="$SELECTED_DISK"
      preserved="nothing on selected disk"
      destroyed="ENTIRE SELECTED DISK: $SELECTED_DISK (GPT, ESP, and every partition)"
      ;;
    free)
      target="sectors $FREE_START-$FREE_END (new Linux partition)"
      partitions=$(lsblk -rpn -o PATH,TYPE "$SELECTED_DISK" | awk '$2 == "part" {print $1}' | paste -sd, -)
      preserved="${partitions:-no existing partitions}, including ESP $ESP_PARTITION"
      destroyed="new partition contents in sectors $FREE_START-$FREE_END"
      ;;
    replace)
      target="$TARGET_PARTITION"
      partitions=$(lsblk -rpn -o PATH,TYPE "$SELECTED_DISK" | awk '$2 == "part" {print $1}')
      preserved=''
      while read -r partition; do
        [[ -n $partition && $partition != "$TARGET_PARTITION" ]] || continue
        if [[ -n $preserved ]]; then preserved+=", "; fi
        preserved+="$partition"
      done <<<"$partitions"
      preserved="${preserved:-none}"
      destroyed="$TARGET_PARTITION"
      ;;
  esac
  gum style --border normal --padding "1 2" "Configuration: $SELECTED_HOST
Hostname: $HOSTNAME
Username: $USERNAME
Physical disk: $SELECTED_DISK
RAM detected: $(format_mib "$RAM_SIZE_MIB")
Disk swap: $(format_mib "$SWAP_SIZE_MIB")
Mode: $INSTALL_MODE
Target: $target
ESP: $ESP_PARTITION
DESTROYED: $destroyed
PRESERVED: $preserved

The scope above is the only data Wintix intends to destroy."
  lsblk -rno PATH,FSTYPE "$SELECTED_DISK" | grep -qi ntfs && warn "Windows/NTFS data was detected on this disk."
  confirm_destructive
}
