#!/usr/bin/env bash

discover_hosts() {
  mapfile -t HOSTS < <(nix eval --json "$WINTIX_FLAKE_REF#nixosConfigurations" --apply 'x: builtins.attrNames x' | jq -r '.[]')
  ((${#HOSTS[@]})) || die "No Wintix NixOS host configurations were discovered."
}

select_host() {
  discover_hosts
  SELECTED_HOST=$(gum choose --header "Select Wintix host" "${HOSTS[@]}")
  # Existing normal users are authoritative. A host with zero or multiple users
  # needs a host-side definition rather than an installer guess.
  mapfile -t NORMAL_USERS < <(nix eval --json "$WINTIX_FLAKE_REF#nixosConfigurations.${SELECTED_HOST}.config.users.users" --apply 'u: builtins.filter (n: u.${n}.isNormalUser) (builtins.attrNames u)' | jq -r '.[]')
  [[ ${#NORMAL_USERS[@]} -eq 1 ]] || die "Host ${SELECTED_HOST} must define exactly one normal user for unattended selection."
  USERNAME=${NORMAL_USERS[0]}
}

select_mode() {
  local choice
  choice=$(gum choose --header "Installation mode" \
    "wipe | Wipe entire disk (all data destroyed)" \
    "free | Use contiguous unallocated space (preserve partitions)" \
    "replace | Replace one existing partition (retain GPT entry)")
  INSTALL_MODE=${choice%% *}
  case $INSTALL_MODE in
    wipe) TARGET_PARTITION=""; ESP_PARTITION="generated by Disko" ;;
    free) require_gpt_for_partial_mode; select_esp "$SELECTED_DISK"; select_free_region ;;
    replace) require_gpt_for_partial_mode; select_esp "$SELECTED_DISK"; select_replace_partition ;;
  esac
}

review_plan() {
  local target preserved destroyed partitions partition
  case $INSTALL_MODE in
    wipe)
      target="$SELECTED_DISK"
      preserved="nothing on selected disk"
      destroyed="ENTIRE SELECTED DISK: $SELECTED_DISK (GPT, ESP, and every partition)"
      ;;
    free)
      target="sectors $FREE_START-$FREE_END (new Linux partition)"
      partitions=$(lsblk -rpn -o PATH,TYPE "$SELECTED_DISK" | awk '$2 == "part" {print $1}' | paste -sd, -)
      preserved="${partitions:-no existing partitions}, including ESP $ESP_PARTITION"
      destroyed="new partition contents in sectors $FREE_START-$FREE_END"
      ;;
    replace)
      target="$TARGET_PARTITION"
      partitions=$(lsblk -rpn -o PATH,TYPE "$SELECTED_DISK" | awk '$2 == "part" {print $1}')
      preserved=''
      while read -r partition; do
        [[ -n $partition && $partition != "$TARGET_PARTITION" ]] || continue
        if [[ -n $preserved ]]; then preserved+=", "; fi
        preserved+="$partition"
      done <<<"$partitions"
      preserved="${preserved:-none}"
      destroyed="$TARGET_PARTITION"
      ;;
  esac
  gum style --border normal --padding "1 2" "Host: $SELECTED_HOST
Username: $USERNAME
Physical disk: $SELECTED_DISK
Mode: $INSTALL_MODE
Target: $target
ESP: $ESP_PARTITION
DESTROYED: $destroyed
PRESERVED: $preserved

The scope above is the only data Wintix intends to destroy."
  lsblk -rno PATH,FSTYPE "$SELECTED_DISK" | grep -qi ntfs && warn "Windows/NTFS data was detected on this disk."
  confirm_destructive
}
